<a href="https://colab.research.google.com/github/Isurajgarg/Credit_Card/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install faker

Collecting faker
  Downloading Faker-24.4.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 11.0 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-24.4.0

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from faker import Faker

In [15]:
fake = Faker()

def simulated_data(num_transcations):
  transaction=[]

  for i in range(num_transactions):
    transaction_date = fake.date_time_between(start_date ='-365d',end_date = 'now')
    transaction_id = fake.uuid4()
    merchant= fake.company()
    name = fake.name()
    country = fake.country()
    amount = np.round(np.random.uniform(100,1000),2)

    category = np.random.choice(['Entertainment','Retail','Electronics','Grocery','Education','Travel'])
    card_category = np.random.choice(['Business','Platinum','Gold'])
    customer_id = fake.random_number(digits=5)

    transaction.append({'Transaction Date': transaction_date,
                        'Transaction ID':transaction_id,
                        'Company':merchant,
                        'Name':name,
                        'Country':country,
                        'Amount':amount,

                        'Category':category,
                        'Card Type':card_category,
                        'Customer ID':customer_id})

  return transaction

In [17]:
num_transactions = 1000

data_1 = simulated_data(num_transactions)
data = pd.DataFrame(data_1)

data.head(20)

,Transaction Date,Transaction ID,Company,Name,Country,Amount,Category,Card Type,Customer ID
0,2023-11-06 03:18:29.510279,63abafed-9ae4-4fa3-bb68-01624435cc0e,Coleman Inc,Mitchell Gomez,South Georgia and the South Sandwich Islands,574.95,Electronics,Platinum,43860
1,2023-12-19 01:42:07.759542,e11e94db-4eb7-4b7e-9118-f80eba3a5e73,Ramos and Sons,Mr. Charles Bennett,Palau,991.55,Entertainment,Gold,34215
2,2023-06-28 07:36:11.714952,74c58dde-876a-4e24-a410-d7c5f79b41c4,"Young, Lawson and Jarvis",Beverly Hancock,Puerto Rico,470.52,Travel,Platinum,35599
3,2023-11-26 17:30:27.251255,112812d9-80a2-4215-a1c5-ab4e3bab1122,Peterson-Hughes,Deborah Blankenship,Malaysia,191.78,Entertainment,Platinum,94721
4,2023-04-18 02:04:30.852117,72afd15b-03c4-4d82-be89-ff36124c486f,"Perez, Martinez and Davis",Alicia Garcia,Cyprus,565.24,Retail,Gold,56001
5,2024-01-14 16:01:10.012388,91aa6ca5-8063-4a5b-a7c7-0fb1c677e161,"Robbins, Young and Henderson",Joseph Smith,Albania,262.68,Electronics,Gold,86580
6,2024-02-05 21:43:32.620054,c92d5f70-eaf4-4645-9906-f98b71fe4634,Hampton and Sons,Michael Green,Micronesia,244.31,Education,Gold,54459
7,2023-09-29 02:46:59.961754,d501b9ea-00a4-4862-aa9a-0efcc57e6df7,Kirk-Meyer,Wesley Miller,Dominican Republic,727.25,Entertainment,Gold,78916
8,2023-05-24 04:37:24.123120,cf34aaf3-2a37-463f-a5b7-57c700ef00ac,Russell-Bell,Donald Cummings,Bhutan,671.28,Retail,Gold,94456
9,2023-05-22 05:14:07.663439,0f70e87a-b31a-4f33-b031-3d6c9b3511f9,Turner-Campbell,James Jordan,British Virgin Islands,768.74,Travel,Platinum,54007
10,2023-09-04 15:06:44.615411,fd23f98f-df24-4c8b-bf57-a9f7a92f9402,Davis-Walters,Ashley Harrison,Vanuatu,488.34,Retail,Gold,10890
11,2023-07-14 00:33:49.551076,354d77c7-b0e7-40ce-9c14-6a00a3eb0bed,"Hardy, Patton and Holt",Christina Travis,Turkey,725.60,Electronics,Business,64385
12,2023-10-18 18:46:51.155943,bbc161ed-fee5-456f-a31a-6aa05c2566b9,"Smith, Benton and Lawrence",Michael Wood,Benin,780.17,Travel,Platinum,56695
13,2023-05-10 07:05:00.563825,05c0e725-c0a6-4811-b4e8-703715d28adb,Jones Ltd,Judy Bowen,Poland,736.84,Travel,Platinum,59083
14,2024-01-05 21:11:37.940202,105e6ba7-e57b-4e5b-a854-823f1aa46cd1,Mueller Ltd,Natalie Huber,Ethiopia,207.55,Grocery,Gold,50950
15,2023-12-07 06:28:55.199615,fcb0633e-b6a6-46ee-8448-1fcf0411062d,"Sanchez, Jones and Brennan",Angela Kelly,Saint Martin,487.15,Entertainment,Business,17098
16,2023-11-06 23:36:29.343425,76f44f2e-5ae2-4207-a521-b27a5cbea81e,Ramirez-Faulkner,Jill Salinas,Mexico,108.72,Education,Business,71856
17,2023-06-24 06:06:03.219904,f65ac6f0-2833-4564-b023-56162d8be951,Gonzales-Garcia,Rachel Smith,Turks and Caicos Islands,201.31,Entertainment,Gold,59995
18,2024-02-14 21:25:56.960216,42ff6198-e6fb-4300-8075-8f08ef16f900,Christensen-Brown,Kevin Carney,French Guiana,135.40,Electronics,Gold,76635
19,2024-02-22 16:16:12.130796,f7988013-3ca0-4a04-b162-6b2d7ab372fd,"Spencer, Cruz and Gonzalez",Shawna Ortiz,Sierra Leone,873.82,Electronics,Gold,24451